# Generated by Django 4.1.1 on 2022-10-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amonic', '0006_alter_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('make_model', models.CharField(max_length=256)),
                ('total_seats', models.SmallIntegerField(verbose_name='Общее количество мест')),
                ('economy_seats', models.SmallIntegerField(verbose_name='Количество мест в эконом-классе')),
                ('business_seats', models.SmallIntegerField(verbose_name='Количество мест в бизнес-классе')),
            ],
            options={
                'verbose_name': 'Самолёт',
                'verbose_name_plural': 'Самолёты',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amonic.country', verbose_name='Страна')),
                ('iata_code', models.CharField(max_length=3, verbose_name='Код аэропорта ИАТА')),
                ('name', models.CharField(max_length=512, verbose_name='Название аэропорта')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flight.airport', verbose_name='Аэропорт вылета')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='flight.airport', verbose_name='Аэропорт назначения')),
                ('distance', models.IntegerField(verbose_name='Дистанция полёта')),
                ('flight_time', models.IntegerField(verbose_name='Время полёта')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата вылета')),
                ('time', models.TimeField(verbose_name='Время вылета')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.aircraft', verbose_name='Самолёт')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.route', verbose_name='Маршрут')),
                ('economy_price', models.IntegerField(verbose_name='Цена билета в эконом-классе')),
                ('confirmed', models.SmallIntegerField(verbose_name='Подтверждён?')),
                ('flight_number', models.CharField(max_length=16, verbose_name='Номер рейса')),
            ],
            options={
                'verbose_name': 'График вылетов',
                'verbose_name_plural': 'Графики вылетов',
            },
        ),
    ]
