# Generated by Django 4.1.1 on 2022-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='logout_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время выхода из системы'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('software_crash', 'Software Crash'), ('system_crash', 'System Crash')], max_length=32, null=True, verbose_name='Причина ошибки'),
        ),
    ]
