# Generated by Django 4.1.1 on 2022-10-05 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonic', '0004_remove_userlog_reason_alter_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 6, 55, 22, 339902, tzinfo=datetime.timezone.utc), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='usercrashreport',
            name='reason',
            field=models.CharField(choices=[('software_crash', 'Software Crash'), ('system_crash', 'System Crash')], default='software_crash', max_length=32, verbose_name='Причина ошибки'),
            preserve_default=False,
        ),
    ]
