# Generated by Django 4.1.1 on 2022-10-06 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonic', '0005_alter_user_birthdate_alter_usercrashreport_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date(2022, 10, 6), verbose_name='Дата рождения'),
        ),
    ]
