# Generated by Django 4.1.1 on 2022-10-13 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amonic', '0006_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='crash_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='amonic.usercrashreport', verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date(2022, 10, 13), verbose_name='Дата рождения'),
        ),
    ]
